<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/8/12
 * Time: 17:01
 */
namespace app\common\model;

use think\Model;

class Base extends Model
{
    protected $table = '';
//    protected $resultSetType = 'array';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->table = strtolower(preg_replace("/(?<=[a-z])([A-Z])/", "_$1", $this->name));
    }
}